### ISSUE TITLE
'vagrant-box-updater' plugin is broken 

### ISSUE THREAD

**Issue by arky** [arky/iiab-smoketest#5]
Vagrant-box-updater plugin is broken on some machines. Please remove it with `vagrant plugin uninstall vagrant-box-updater`. 

Ruby Gem Error:
> 
 > .vagrant.d/gems/2.3.4/gems/vagrant-box-updater-0.0.3/lib/vagrant-box-updater/util/common.rb:7:in `get_path_box_stat_file': uninitialized constant Psych::ENGINE (NameError)
>         from /home/arky/.vagrant.d/gems/2.3.4/gems/vagrant-box-updater-0.0.3/lib/vagrant-box-updater/action/up_box.rb:19:in `call'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:227:in `action_raw'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:202:in `block in action'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:631:in `lock'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:188:in `call'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:188:in `action'
>         from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by arky** [comment]
The vagrant-box-updater is no longer actively maintained. Removed it from the project. 

https://github.com/arky/iiab-smoketest/commit/56b6a481cda1450e789f8b3ad67a9548bdf9b706
